#!/bin/sh -e

. /usr/share/debconf/confmodule

# Changing these will only influence new certificates
db_input high arrowhead-common/cloudname || true
db_input high arrowhead-common/operator || true
db_input high arrowhead-common/company || true
db_input high arrowhead-common/organisation || true
db_input high arrowhead-common/country || true

# We do not yet support changing passwords...
db_get arrowhead-common/mysql_password
if [ -z "$RET" ]; then
    db_input high arrowhead-common/mysql_password || true
fi
db_get arrowhead-common/cert_password
if [ -z "$RET" ]; then
    db_input high arrowhead-common/cert_password || true
fi
db_go || true

adduser --system --no-create-home --group arrowhead

mkdir -p /etc/arrowhead/cert

if [ ! -d /var/log/arrowhead ]; then
    mkdir -p /var/log/arrowhead
    chown arrowhead:adm /var/log/arrowhead
    chmod 750 /var/log/arrowhead
fi

db_get arrowhead-common/mysql_password
if [ -z "$RET" ]; then
    PASS="$(openssl rand -base64 12)"
    db_set arrowhead-common/mysql_password ${PASS}
fi

db_get arrowhead-common/cert_password
if [ -z "$RET" ]; then
    PASS="$(openssl rand -base64 12)"
    db_set arrowhead-common/cert_password ${PASS}
fi

. /usr/share/arrowhead/conf/ahconf.sh

ah_cert /etc/arrowhead/cert master "arrowhead.eu"
ah_cert_signed /etc/arrowhead/cert cloud "${AH_CLOUD_NAME}.${AH_OPERATOR}.arrowhead.eu" /etc/arrowhead/cert master
ah_cert_trust /etc/arrowhead/cert /etc/arrowhead/cert cloud
