#!/bin/sh -e

. /usr/share/debconf/confmodule

# We do not yet support changing values...
db_get arrowhead-common/cloudname
if [ -z "$RET" ]; then
    db_input high arrowhead-common/cloudname || true
fi
db_get arrowhead-common/operator
if [ -z "$RET" ]; then
    db_input high arrowhead-common/operator || true
fi
db_get arrowhead-common/company
if [ -z "$RET" ]; then
    db_input high arrowhead-common/company || true
fi
db_get arrowhead-common/organisation
if [ -z "$RET" ]; then
    db_input high arrowhead-common/organisation || true
fi
db_get arrowhead-common/country
if [ -z "$RET" ]; then
    db_input high arrowhead-common/country || true
fi
db_get arrowhead-common/mysql_password
if [ -z "$RET" ]; then
    db_input high arrowhead-common/mysql_password || true
fi
db_get arrowhead-common/cert_password
if [ -z "$RET" ]; then
    db_input high arrowhead-common/cert_password || true
fi
db_go || true

mkdir -p /etc/arrowhead/cert

if [ ! -d /var/log/arrowhead ]; then
    mkdir -p /var/log/arrowhead
    chown arrowhead:adm /var/log/arrowhead
    chmod 750 /var/log/arrowhead
fi

db_get arrowhead-common/mysql_password
if [ -z "$RET" ]; then
    PASS="$(openssl rand -base64 12)"
    db_set arrowhead-common/mysql_password ${PASS}
fi

db_get arrowhead-common/cert_password
if [ -z "$RET" ]; then
    PASS="$(openssl rand -base64 12)"
    db_set arrowhead-common/cert_password ${PASS}
fi

db_get arrowhead-common/cert_password; PASS_CERT=$RET
db_get arrowhead-common/cloudname; CLOUDNAME=$RET
db_get arrowhead-common/operator; OPERATOR=$RET
db_get arrowhead-common/company; COMPANY=$RET
db_get arrowhead-common/organisation; ORGANISATION=$RET
db_get arrowhead-common/country; COUNTRY=$RET

if [ ! -f "/etc/arrowhead/cert/master.p12" ]; then
    keytool -genkeypair \
        -alias master \
        -keyalg RSA \
        -keysize 2048 \
        -dname "CN=arrowhead.eu, OU=${ORGANISATION}, O=${COMPANY}, C=${COUNTRY}" \
        -validity 3650 \
        -keypass ${PASS_CERT} \
        -keystore /etc/arrowhead/cert/master.p12 \
        -storepass ${PASS_CERT} \
        -storetype PKCS12

    chown :arrowhead /etc/arrowhead/cert/master.p12
    chmod 640 /etc/arrowhead/cert/master.p12
fi

if [ ! -f "/etc/arrowhead/cert/cloud.p12" ]; then
    keytool -genkeypair \
        -alias cloud \
        -keyalg RSA \
        -keysize 2048 \
        -dname "CN=${CLOUDNAME}.${OPERATOR}.arrowhead.eu, OU=${ORGANISATION}, O=${COMPANY}, C=${COUNTRY}" \
        -validity 3650 \
        -keypass ${PASS_CERT} \
        -keystore /etc/arrowhead/cert/cloud.p12 \
        -storepass ${PASS_CERT} \
        -storetype PKCS12

    keytool -export \
        -alias master \
        -storepass ${PASS_CERT} \
        -keystore /etc/arrowhead/cert/master.p12 \
    | keytool -import \
        -trustcacerts \
        -alias master \
        -keystore /etc/arrowhead/cert/cloud.p12 \
        -keypass ${PASS_CERT} \
        -storepass ${PASS_CERT} \
        -storetype PKCS12 \
        -noprompt

    keytool -certreq \
        -alias cloud \
        -keypass ${PASS_CERT} \
        -keystore /etc/arrowhead/cert/cloud.p12 \
        -storepass ${PASS_CERT} \
    | keytool -gencert \
        -alias master \
        -keypass ${PASS_CERT} \
        -keystore /etc/arrowhead/cert/master.p12 \
        -storepass ${PASS_CERT} \
    | keytool -importcert \
        -alias cloud \
        -keypass ${PASS_CERT} \
        -keystore /etc/arrowhead/cert/cloud.p12 \
        -storepass ${PASS_CERT} \
        -noprompt

    chown :arrowhead /etc/arrowhead/cert/cloud.p12
    chmod 640 /etc/arrowhead/cert/cloud.p12
fi

if [ ! -f "/etc/arrowhead/cert/truststore.p12" ]; then
    keytool -export \
        -alias cloud \
        -storepass ${PASS_CERT} \
        -keystore /etc/arrowhead/cert/cloud.p12 \
    | keytool -import \
        -trustcacerts \
        -alias cloud \
        -keystore /etc/arrowhead/cert/truststore.p12 \
        -keypass ${PASS_CERT} \
        -storepass ${PASS_CERT} \
        -storetype PKCS12 \
        -noprompt

    chown :arrowhead /etc/arrowhead/cert/truststore.p12
    chmod 640 /etc/arrowhead/cert/truststore.p12
fi
